# Generated by Django 4.0.6 on 2022-07-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idstudent', models.IntegerField()),
                ('fnamestudent', models.CharField(max_length=45)),
                ('lnamestudent', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
