version: '3.9'
services:
    db:
      image: mysql:5.7.38
      ports:
        - "3306:3306"
      restart: always
      environment:   
        MYSQL_ROOT_PASSWORD: '12345'
        MYSQL_ROOT_HOST: '%'
        MYSQL_USER: 'user'
        TZ: Turkey
      volumes:
        - "vol1:/var/lib/mysql"
    
    python:
      build: 
        context: ./
        dockerfile: Dockerfile
      volumes:
      - "./src:/app"
      ports:
      - 8000:8000
      depends_on:
      - mysql-db

volumes:
  vol1:
